unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product_Hierarchy
    label: Product Hierarchy
    levels:
      - unique_name: Product_Level
is_degenerate: true
level_attributes:
  - unique_name: Product_Level
    label: Product Level
    contains_unique_names: false
    shared_degenerate_columns:
      - dataset: HoleFoods Sales
        key_columns:
          - Product
        name_column: Product
      - dataset: HoleFoods Product
        key_columns:
          - Category
        name_column: Category
type: standard
