unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    levels:
      - unique_name: Category
      - unique_name: Name
is_degenerate: true
level_attributes:
  - unique_name: Category
    label: Category
    contains_unique_names: false
    dataset: HoleFoods Product
    is_unique_key: false
    key_columns:
      - Category
    name_column: Category
  - unique_name: Name
    label: Name
    contains_unique_names: false
    dataset: HoleFoods Sales
    is_unique_key: false
    key_columns:
      - Product
    name_column: Product
type: standard
